### ISSUE TITLE
Widget Mini Calendar drop down errors.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#102]
The Limit by Author and Limit by Host are both drop downs but does not show it properly.
Here is an example of Limit by Host active drop downs.

![Screen Shot 2021-07-16 at 17 05 43](https://user-images.githubusercontent.com/5323259/125968914-2311db33-645b-4cb4-bb56-502fdbad9c61.png)

**Comment by joedolson** [comment]
What is the issue? I'm not following. Unless you mean 'dropdown' in the literal sense, rather than in the 'dropdown is another term used for the select input'. This is the latter, but not the former.

**Comment by paaljoachim** [comment]
The down arrow is partly covered by the right edge.

**Comment by joedolson** [comment]
Ah. Also, there shouldn't be a down arrow, because this is a multiselect. That looks like a problem with core styles for selects not accounting for multi select. (Core is replacing the browser's down arrows on selects.)

**Comment by joedolson** [comment]
Where does this screenshot come from? Is it the block widget tool? This is what I see:

![image](https://user-images.githubusercontent.com/1686451/125980665-432a35d0-0ca2-4882-8182-dbf7d63c0f58.png)

**Comment by joedolson** [comment]
Ah, it's just specific to selected items; and the fact that the up/down arrows don't appear for you is just because of the number of users. Got it.

I think this is a wontfix; it's a core CSS thing. I haven't found any information about how to use plugin CSS in legacy widgets, so I'm not going to prioritize this right now.
