### ISSUE TITLE
Saving as draft and continue editing - left sidebar menu shows Add Event as active.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#110]
I saved an event as a draft and continued editing.
I noticed this in the sidebar:

![Screen Shot 2021-07-19 at 12 14 06](https://user-images.githubusercontent.com/5323259/126144828-bb467bb2-c6ef-43fb-a113-465ce783605a.png)

Add Event is highlighted. Events should be highlighted.

**Comment by joedolson** [comment]
This is, technically, the Add Event screen. The title element does change to reflect that you're editing an event; but the screen is for the create/edit event form. 

I'm aware that WordPress core highlights the post type group when editing, but in all honesty I think it's pretty arbitrary - neither of those are actually the "current" page, and I don't think that either of them really *should* be highlighted. 

I'm going to leave this as is, rather than jump through all the hoops it would take to either re-map the code base or fake the current page, since I don't see the end result as particularly valuable.
