### ISSUE TITLE
Scheduled dates for this event

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#111]
I added a repeated pattern to an event. Then went to continue editing.

Scheduled dates for this event is added below the Date and Time section. (Usually where add occurrence is located.)

![Screen Shot 2021-07-19 at 12 20 54](https://user-images.githubusercontent.com/5323259/126145682-ef1e27a9-c5f2-416d-abdc-4eec13d94667.png)

What about moving the Scheduled dates for this event into the Repetition Pattern area?
(I added the Add another occurrence button in the below mockup which is currently missing from this page. Added an issue for it here: #99 )

![My-Calendar-move-Scheduled-dates](https://user-images.githubusercontent.com/5323259/126146489-69537417-d5e0-48f2-bb11-69df2646f1ea.jpg)

**Comment by joedolson** [comment]
I'm going to take a different strategy. Right now, if you've customized the dates within a repetition pattern, then you edit the event, it'll wipe out your customizations. Because of that, I'm going to turn off changing the repetition pattern when editing an event with additional scheduled dates. I'll add a button for users to enable it, with a warning that it'll wipe out their customized dates.

**Comment by joedolson** [comment]
Made some extensive changes here: https://github.com/joedolson/my-calendar/commit/d8c40f34df69183392c30b7eb2225b198c4f2deb

**Comment by joedolson** [comment]
I think that this is finished; if there are further issues, please reopen.
