### ISSUE TITLE
Adjusting how Scheduled dates are seen in the backend in the root event

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#113]
Currently Scheduled dates for this event looks like this:

![Scheduled-dates-for-this-event-original](https://user-images.githubusercontent.com/5323259/126147100-bbf07dfd-2761-45fc-ac7d-277a1f26d044.jpg)

What if we made it into a list. 
(I repeated a bulk of dates to show as an example.)

![Scheduled-dates-for-this-event-ver1](https://user-images.githubusercontent.com/5323259/126150280-1c82e5ec-4470-40c9-95f3-c6e0abb45e8a.jpg)

![Scheduled-dates-for-this-event-ver2](https://user-images.githubusercontent.com/5323259/126150287-4164b03b-863c-4dae-8c30-0f0e8c628d66.jpg)

![Scheduled-dates-for-this-event-ver3](https://user-images.githubusercontent.com/5323259/126150303-fafa0c06-b8bb-4888-859d-51d147d80b88.jpg)

Creating a list brings a clearer overview of the time and dates. One could also add more information if needed. Perhaps adding in the location or parts of the excerpt or other information. As it would create a nice overview of the repeated events.

**Comment by joedolson** [comment]
I've always been hesitant about bringing in a bunch of information that's just going to repeat over and over. The only thing different about these dates is the dates; the titles, locations, etc. are always going to be the same for every event. I think it would just add a lot of noise to repeat that over and over again. 

The list is plausible. It is an advantage to be able to see the sequence of dates more easily. One thing I should do is incorporate the full date/time info - since these sub events can have different lengths.

**Comment by paaljoachim** [comment]
> One thing I should do is incorporate the full date/time info - since these sub events can have different lengths.

That sounds like a good idea!

**Comment by joedolson** [comment]
I'm going to shift this off to 3.4.0 for future consideration. Full date/time info is in place; but I'm just not decided on this. It's not a particularly major shift, but I"m not sure "align the date information" is enough reason to have this end up having that much empty space.
