### ISSUE TITLE
Settings -> Input -> Host vs Settings -> Output -> Author's name.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#157]
I noticed that Settings -> Input uses the word Host

![Screen Shot 2021-07-27 at 21 19 15](https://user-images.githubusercontent.com/5323259/127215055-82825ded-f7f1-471b-95f6-dac41a8aca3c.jpg)

While Settings -> Output uses the word Author's name.

![Screen Shot 2021-07-27 at 21 19 31](https://user-images.githubusercontent.com/5323259/127215135-b8d00b0a-b825-4381-80e9-ed40db0044b2.jpg)

There is also the Event Details section in the Event page.
(Here I made a new WP user which I called tester.)

![Screen Shot 2021-07-27 at 21 23 47](https://user-images.githubusercontent.com/5323259/127215361-5783e06c-bd89-462a-b789-ff9221595502.jpg)

Went to view the event on the frontend and noticed it said "Posted by joachim" I assume this would be posted by tester.

I am a little confused by the use of Author's name and host.

**Comment by joedolson** [comment]
The author is "the person who published this event"; the host is "the person assigned to host"

There are a number of fields that don't currently have any default output in the standard setup, and can only be produced in custom stylesheets, and host is one of those.

**Comment by paaljoachim** [comment]
It sounds like we need to add host into the default output. User could select to show author and/or host in the output.

**Comment by joedolson** [comment]
Also adds a complication that for many users the 'host' is always going to be the same as the author. It's always saved; it's just that it's usually the same value as the author, unless set otherwise. That could lead to confusion for some users, as well. Trying to think this through...

At some level, I should probably just have an option for outputting every piece of information - it's ultimately up to the user to figure out whether they actually want it. And at least it'll always output something.

**Comment by paaljoachim** [comment]
Yeah. It can be confusing to show author and host. As it really crosses over into each other.
I would think that for an event the host information is what is important. (It depends on how users have been using author and host...)

Should there be added information if a user wants to show host information? As in host name and some background info on the host etc?

**Comment by joedolson** [comment]
There is additional information available when doing custom templates. Some major updates to the default templating configuration is probably not good for this release - I think that's a good candidate for the next one after this. But I want to focus more on UI in this release. That way I'm making a release that shouldn't have any breaking changes to speak of on the front-end. Then, in the next release, I'm aiming to allow for front-end breaking changes - because I'm going to need to accept that if I'm going to modernize the front-end. But I want to make sure everybody gets the UI/UX improvements first.

**Comment by joedolson** [comment]
I'm adding 'host' to the configuration because it improves clarity, but I'm not going to make other extensive changes at this point.

**Comment by paaljoachim** [comment]
That sounds like a very good way of tackling it!

**Comment by joedolson** [comment]
I think this should actually already be closed...
