### ISSUE TITLE
Adjusting the Manage Locations screen.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#161]
Here is the current Manage Location screen:

![Screen Shot 2021-07-27 at 22 10 57](https://user-images.githubusercontent.com/5323259/127220806-2657b057-7e74-45f8-9ad7-8e00059ba287.jpg)

Top Delete locations button is greyed out and bottom Delete locations is blue in the current setup.

Here is the adjustment:
![Manage-Locations-adjustments](https://user-images.githubusercontent.com/5323259/127220838-b5558504-f445-4380-85a5-17fac1d640b2.jpg)

Adjustments I made:
Removed the Default Location section in the right sidebar.
Added a Default button next to a Delete (locations) button. Removed the word locations from the top and bottom buttons.

Permalink link I added to this issue: https://github.com/joedolson/my-calendar/issues/160

**Comment by joedolson** [comment]
I don't think it's necessary to take up screen space with a 'Default' button - that'll be a very infrequently used option, since for most sites where it's helpful it would probably be changed *very* rarely. I think that editing that in the event is sufficient. 

The other button changes seem reasonable and consistent with elsewhere.

**Comment by joedolson** [comment]
Note: I'm going to keep 'Delete Locations' as the text, however. I prefer buttons that give full context for what they will do, and there are no space issues here that would require shortening that.
