### ISSUE TITLE
Selecting a current location and adding it to an event.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#162]
I have added two locations.
In the event location drop down I selected a location.

![Screen Shot 2021-07-27 at 22 18 39](https://user-images.githubusercontent.com/5323259/127221746-fa5f39cb-a225-4115-a942-9d01889cc272.jpg)

1 - I select a pre-made location.
2 - "Copy this location into the locations table" I assume will copy/use the location I selected in the drop down.
3 - I click the update button and notice the location added to the event location information. 

![Screen Shot 2021-07-27 at 22 23 29](https://user-images.githubusercontent.com/5323259/127222302-b3b68f4c-bfa4-4d3c-b723-181328466487.jpg)

Click the link: Current location: Opsal Gard (Opens in new tab)
The link just opens the Edit Location page.

A few things I notice:

1 - Drop down shows a -- (after having added the location to the event page.) It should still say the location name: Opsal Gard.

Descriptions are somewhat confusing:

2- "Copy this location into the locations table."
Could be rephrased to: "Copy this location into the event locations table." 

3 - Current location: Opsal Gard (Opens in new tab)
Could be rephrased to: Open the current location in the Edit Location screen/page (Opens in a new tab)

As the Current location: Opsal Gard does not say where the link will go to.
I am not sure if we are using the phrase screen or page. Which I mention just above here.

**Comment by joedolson** [comment]
In my opinion, any situation where you're using *both* the location dropdown and the location input form is going to be inherently awkward. Overall, I'd rather just discourage that. It's historical; older installations may only have location data in the event fields, and need to be able to modify it there. But it's not preferred, for sure. 

There are a number of historical reasons for some of the oddities here, but the upshot is that most of this is in a 'wontfix' (or at least in a "not yet") area, due to some backwards compatibility problems. 

I think the text for the location could just be _Edit "Opsal Gard"_, or something to that effect. 

I generally prefer the word 'Screen'.

**Comment by paaljoachim** [comment]
"Current location: Opsal Gard (Opens in new tab) "
---> Edit "Opsal Gard" is nice and short.

**Comment by paaljoachim** [comment]
This is what it looks like right now (where I have also selected it as a default location):
![Screen Shot 2021-07-31 at 14 36 57](https://user-images.githubusercontent.com/5323259/127740078-3b6052ef-ee52-4d4a-bf84-eff749f17a39.jpg)
