### ISSUE TITLE
My Calendar Styles - moving Select Stylesheet into the main content area.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#163]
Moving the Select Stylesheet section into the main content area.

Current:
![Screen Shot 2021-07-27 at 22 40 36](https://user-images.githubusercontent.com/5323259/127224351-9744b428-027c-4fed-92da-c50dc72422d1.jpg)

Adjustment suggestion:
![My-Calendar-Styles-moving-Choose-style-to-main-content](https://user-images.githubusercontent.com/5323259/127225398-605166e7-9d5d-4039-b027-ba87cace7c8c.jpg)

I moved the Select Stylesheet section into the main content area.
Moved Calendar Style Settings into the top of this box.

**Comment by paaljoachim** [comment]
A followup....
I moved the "Reset to default" - What default?
and I also moved the "Disable My Calendar Stylesheet" - What is the alternative?

![Style-Settings-moved-settings-ver2](https://user-images.githubusercontent.com/5323259/127232163-a80121ef-ad44-482c-a240-75d9388afea5.jpg)

**Comment by joedolson** [comment]
It used to be there, but I moved it because people could never find it, for some reason. It's a mystery to me *why* that was a problem, but the support requests have gone down since moving it. 

So as much as I agree that in principle this should be in the main content, evidence suggests not. 

:shrug:

- Reset to default: probably, I should only show this option if the version of the stylesheet being viewed doesn't match the core version. It resets the stylesheet to match the version currently shipped in the plug-in, removing any customizations, changes, etc.

- Disabled My Calendar stylesheet: the alternative is... not disabling the stylesheet? I don't understand your question. If you just don't want My Calendar to load its own styles, and use all your own, then you'd disable the stylesheet.

**Comment by paaljoachim** [comment]
Hmm.... I believe this has to do with people are used to seeing the publish button in the top right corner.
Disabling the My Calendar stylesheet gives the user the opportunity to copy CSS classes into the customizer or the current theme stylesheet or somewhere else. I see that now.

O'well we move on....
