### ISSUE TITLE
Inspiration - wp event calendar

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#179]
I happen to come across JJJ's old calendar plugin.

https://wordpress.org/plugins/wp-event-calendar/

All Events
![Screen Shot 2021-08-15 at 22 59 40](https://user-images.githubusercontent.com/5323259/129492792-ab4dc14b-a3a8-4a15-93e2-b9bffbeb8177.jpg)

Uses filtering.

Add New

![Screen Shot 2021-08-15 at 23 04 02](https://user-images.githubusercontent.com/5323259/129492851-d23608a8-a1b3-407a-8c90-6352bcbf5673.jpg)

Uses the standard WP right side panels.

Types

![Screen Shot 2021-08-15 at 23 06 34](https://user-images.githubusercontent.com/5323259/129492913-ab887533-7a42-4ba5-943d-0608751fdc5c.jpg)

Types - Categories - Tags 
Shows a standard category or tags screen.

![Screen Shot 2021-08-15 at 23 07 29](https://user-images.githubusercontent.com/5323259/129492925-cc4ec22f-661b-4bfe-a41d-4f82b10deac9.jpg)

Calendar screen.
Shows events as these are created.

The reason for adding screenshots from wp-event-calendar is that there are some standard classic WordPress screens that I believe we can use to inspire My Calendar.

**Comment by joedolson** [comment]
Adding a calendar view for admin navigation of events has been on my roadmap for a while, but the rest of this is easy for that plug-in because it uses WP post types natively; My Calendar has a fully custom UI, so this would be a pretty huge project. 

Happy to have an issue open for integrating the admin calendar view, but the rest of this is a low priority *mostly* because of the amount of work involved.
