### ISSUE TITLE
Rethinking the Template Editor

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#185]
This came up here: https://github.com/joedolson/my-calendar/issues/138#issuecomment-907474100

An example. Doing some brainstorming....

I go to the Template Editor. See various Templates. Wonder what these look like compared to the default.
I begin looking for a way to compare the default vs each template.

Perhaps the templates should be default templates that are enabled on by default. I click somewhere to view the default templates and what these look like today. Then see something I would like to customize.
I go back to the Template Editor screen to duplicate a template to make various customizations to it. Then disable the default e.g grid to instead use my own custom grid template. This way I can go through the default templates and see which I want to change. Duplicate these and customize them, and turn off the default templates and instead use my own customizations of these. I always have the default templates to go back to if I feel like doing so.

**Comment by joedolson** [comment]
Because the current templating system has basically zero parity between the structure of the default format & any custom templates, this isn't really a viable path. There is no such thing as a "default template" that can be reproduced using the custom templates as they stand right now.

That said, for version 2 of templating, something along these lines will be more possible. Not sure how that will play out in terms of a UI for template editing, but we'll see.

**Comment by joedolson** [comment]
Practically speaking, with the new templating, there won't be a template editor. Since all new templates are file-based, rather than database based, I don't want to provide file editing mechanisms. The templates screen will now pretty much just be some documentation and reference to the docs for more information. 

However, with the PHP templates, the templates actually *are* what's used by default, so they'll always be available as a point of reference.
