### ISSUE TITLE
Move bottom Events links to the bottom?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#195]
The bottom event links section just feels out of place between "Special scheduling options" section and the "Preview Template Output" section.

![Screenshot 2021-09-09 at 14 34 23](https://user-images.githubusercontent.com/5323259/132686596-aa53fe9c-7dac-48a0-a33a-a9fe9739e6b3.jpg)

Should it be moved below the "Preview Template Output" section?

**Comment by joedolson** [comment]
Happy to consider design changes that make the event controls make sense where they are; but I don't want to move them below the preview. 

The event controls should be available as part of the editing process - if somebody finishes editing their event, they shouldn't have to either scroll all the way to the bottom or all the way to the top in order to save changes.
