### ISSUE TITLE
Testing Bulk actions drop down. Approving an already approved event shows error message.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#203]
I am testing the various Bulk actions drop downs actions.
![Screenshot 2021-09-13 at 12 16 10](https://user-images.githubusercontent.com/5323259/133066783-b7eb32db-bf4a-4bd3-98ca-d397462ac724.jpg)
 
Publish, Delete, Trash, Approve, Archive and Spam all work.
One thing though...
If one clicks to approve a published event one will see the following error message:

![Screenshot 2021-09-13 at 12 16 03](https://user-images.githubusercontent.com/5323259/133066979-c238cf91-62a2-4dc8-97f8-0676b711f09d.jpg)

Changing the error message might be helpful. Perhaps to something like: Check to see if the event has already been published or something like that.

**Comment by joedolson** [comment]
That's reasonable. I can make some improvements to these messages to handle this case better. It's a technically accurate message - since 'approved' and 'published' are synonymous, but not exactly helpful.

Note: I added the bulk action to 'publish' in this change, as well. It's technically exactly the same thing as published. I may decide to remove the 'approved' option. The only reason to keep it is because people may be looking for it, and not recognize that publish means the same thing - but I think that the language 'publish' is really more clear, overall. 

Thoughts?

**Comment by paaljoachim** [comment]
Approve/Publish does the same thing, so I see no point in having Approve in the drop down list.
We could perhaps change Approve to Draft. As it would take a Published event and change the status to Draft.

A sidetrack but related. Why is Spam in the list?

**Comment by joedolson** [comment]
Hmm. Given that My Calendar doesn't include a method to report Spam, that's a good point. Not really needed.

**Comment by joedolson** [comment]
Already added Draft; I'd noticed that was missing.

**Comment by joedolson** [comment]
Note: there are some spam related features that turn on automatically if Akismet is enabled & connected.

**Comment by paaljoachim** [comment]
It feels tighter and has a better clarity!

![Screenshot 2021-09-13 at 21 08 42](https://user-images.githubusercontent.com/5323259/133142604-7f4d94aa-0e79-4880-896e-7ed943411f55.jpg)

I have some questions I will follow up in a new issue.
