### ISSUE TITLE
Searchable mc-events Post Type

### ISSUE THREAD

**Issue by shankj3** [joedolson/my-calendar#23]
We have a client that needs to be able to search for any page in their site with a global search bar. Could the `exclude_from_search` post type argument be modifiable through a filter?

**Comment by joedolson** [comment]
Hi, @shankj3 - sorry for the delay in response; I've been on vacation the last couple weeks. 

Yes, it's possible to do this - but I'm not sure it'll give you the results you'll want. It might, if you disallow recurring events, but recurring events are not represented as posts; they're just date references associated with a given event post. So your search will be able to find event data, but it'll be problematic as regards individual dates. 

There are ways you can get around this problem using templating - it's possible to display a list of all recurring dates for a given event in the template, so that you can view the event information and still have access to all the unique date information.

**Comment by shankj3** [comment]
No worries, Joe! Thanks for responding. With our work searching by dates in a search bar isn't a requirement, we just need to be able to search for the post content. If I update my [PR](https://github.com/joedolson/my-calendar/pull/24) with a disclaimer comment on using `mc_event_exclude_from_search`, would that be acceptable?

**Comment by joedolson** [comment]
Certainly, that would be fine. I just need people to know that doing this won't provide a true event search.

**Comment by shankj3** [comment]
Great, just updated!

**Comment by AcriCAA** [comment]
Hi, 

I am working on enabling search for this for a large institutional client. How exactly would you recommended filtering that? I can only make it searchable by adding an action and hooking into `init` but not sure that is the best approach.  Isn't this `mc_events()` function run through various other functions when setting up the post type.

**Comment by joedolson** [comment]
What exactly are you wanting to enable? Are you trying to do the same thing that @shankj3 did - enabling search via a global search tool? As I commented here, before, searching events by searching on the post type is limited; but it depends on what you really want to do. 

I'm not sure what you mean by `mc_events()` function; that's not the name of any function in My Calendar.

**Comment by AcriCAA** [comment]
Apologies @joedolson I meant the `mc_post_type()` function (typo).  Yes I am trying to do the same thing @shankj3 did - enabling search via a global search tool. I understand it is limited and am fine with the limitation.  @shankj3 refers to a filter but I was only able to do it through an action. I feel a filter would be more performant.  Changing this to `false` in the plugin code itself effects the change I want in the search results: `'exclude_from_search' => apply_filters( 'mc_event_exclude_from_search', true ),` in `mc_post_type()`.  But obviously do not want to do that and should do it with a filter.

**Comment by joedolson** [comment]
There's no technical difference between a filter and an action except for what they need to return: a filter generally needs to have a return value, an action doesn't. So from a performance perspective, there's no difference. 

You should be using a filter; but you may need to use an action to set up the filter, so you can have the filter run at the right time.
