### ISSUE TITLE
Editing event: Edit Event Post (?)

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#252]
Clicking to Editing an event the option to "Edit Event Post" showed up which I found a bit confusing.

![Screenshot 2021-09-27 at 22 46 13](https://user-images.githubusercontent.com/5323259/134982767-8efc4d89-adeb-4072-b76d-81f8dee1ca9f.jpg)

It seems that clicking "Edit Event Post" will bring the event to the regular Posts area. I am not sure where this Event post is located. 

![Screenshot 2021-09-27 at 22 46 37](https://user-images.githubusercontent.com/5323259/134982827-b538fa9c-8a24-4540-99e0-0a6f18d429d9.jpg)

I checked under All Posts screen but could not see it. 

Clicking "Edit Event Post" felt like entering the Twilight Zone. As I entered something unexpected and outside the regular event flow. I have no idea why it is there.

**Comment by joedolson** [comment]
So, that's fair. It's a bit complicated. My Calendar events are managed independently, via the My Calendar event manager. However, they use a custom post type to manage custom fields. A common request is to provide support for custom field managers (e.g. Advanced Custom Fields) for My Calendar. That would be very difficult to do in the custom event manager, but trivial by editing the post behind it. I can't really just take this option away, because there are people using it...

It's tricky.

**Comment by paaljoachim** [comment]
No need to remove it. I just need to find a good way to explain each option of the Edit Event menu. So users who are wondering can check the Edit Event documentation.

**Comment by paaljoachim** [comment]
I have gradually began work on: https://docs.joedolson.com/my-calendar/my-calendar-edit-events/
