### ISSUE TITLE
Editing event - clicking update removes Start and End time

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#254]
Editing an event: Clicking Update removes the Start and End time.
![Screenshot 2021-09-27 at 23 33 25](https://user-images.githubusercontent.com/5323259/134988576-85fb7df0-50a7-49f1-a9c1-1cb85dacedbc.jpg)

![Screenshot 2021-09-27 at 23 33 16](https://user-images.githubusercontent.com/5323259/134988587-e16d2e95-7c69-4779-b9bd-597c56170392.jpg)

**Comment by paaljoachim** [comment]
I also noticed that clicking Update removes any additional dates added in Scheduled dates for this event.
Clicking Add another date shows this:
![Screenshot 2021-09-27 at 23 36 07](https://user-images.githubusercontent.com/5323259/134988874-c65dc239-a3cc-4b2d-8f35-9e1fae781ed1.jpg)

**Comment by joedolson** [comment]
That's weird, and I can't currently replicate it. What's your browser environment?

**Comment by paaljoachim** [comment]
I am using Chrome with a local site. I just tested it again. 

Btw do we need the date and time to show like this: 2021-10-16 12:00:00 ?
Can we remove the last two :00 for seconds?

https://user-images.githubusercontent.com/5323259/135121130-c1796833-10da-4576-b17f-45f25b2a81ec.mp4

**Comment by joedolson** [comment]
What, you don't think the seconds are critical? Maybe I should add them to every display time, and add a field for them, so people can schedule events for 12:03:37.

Looking at the video, it appears that you were not able to reproduce the removal of start/end times in this test; is that correct? Is this the same environment you previously tested in?

Obviously, something like data loss when saving is a big deal; so if we can reproduce this, I want to figure it out.

**Comment by paaljoachim** [comment]
We could do a if you a 11:44:33, 10:22:33 and create some fun combinations..:)

The video shows:
1- Adding another date. (Oct 16 2021)
2- It shows up beside the September 30, 2021
12:00 pm-4:00 pm
Editing now 
3- I click update. (Mostly outside the screen.) It updates.
4- I scroll down to Scheduled dates for this event and see only this:
![Screenshot 2021-09-28 at 20 02 15](https://user-images.githubusercontent.com/5323259/135141073-e7fdcf32-4a3c-4b3b-9af1-017cb5ff82f3.jpg)

The Oct 16 date should also show up there.

**Comment by joedolson** [comment]
I simply haven't been able to reproduce this; I must be missing some piece of information. 

Here's what I'm doing:

 - Create a single event
 - Add an additional occurrence
 - Go to edit that single occurrence (the 'Editing now' text tells me that you're editing a single occurrence, rather than a parent event)
 - a) edit the event (both without changes, and with changes). Without changes, nothing happens, as expected. With changes, the event is split & a section of related events is added. But the time remains as expected.
 - b) Add new events, then edit the event. Without changes, this is totally as expected. With changes, the event is split.

Can you give me a detailed list of steps that you can use to reproduce this?

**Comment by paaljoachim** [comment]
Hmm I began creating a video, and I believe I was making a mistake. (human error it seems)

I will look closer into why I made a mistake and see if there is any adjustments we need to fix.

Closing this issue.
