### ISSUE TITLE
Setting Output: Event Display Fields - default preclicked checkboxes

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#256]
This is really nice!
![Screenshot 2021-10-01 at 10 00 26](https://user-images.githubusercontent.com/5323259/135585963-ff1e6ced-72bd-4589-ad40-6678b0c535a7.jpg)

The above only the Share to Google Calendar is prechecked.
Let's instead have these as defaults: Host, Location Address, Description, Featured Image (yes/no?), External link and Accessibility information. I will also assume that it should be External Link (capital L) and Accessibility Information (capital I)

Calendar Popup
Default fields: Host, Location Address, Excerpt, Featured Image, External Link, More details link (More Details Link? - capital letters) and Accessibility information.

List View
Default fields: Host, Location Address, Excerpt, External Link and More Details Link.

Mini Calendar Popup
Default fields: Host, Location Address, Excerpt, External Link and More Details Link.

**Comment by joedolson** [comment]
Did you do a clean re-install? If you didn't, the  you're not seeing the defaults. What I see in that screen is definitely *not* the default. 

The List view and Calendar popup should be equivalent; I'm actually not totally sure I should even have separate settings for them - if they're different, that opens the possibility that users on mobile could see incomplete information, which is fuzzy. 

However, since a user could disable one or the other view, as well, that makes things complicated. For now, I want the List and Popup defaults to be the same.

**Comment by paaljoachim** [comment]
You are right this was not a clean install. I did one just now where I checked "drop MySQL tables on uninstall" and "Delete plugin settings on uninstall"

All options are checked by default for Single Event, Calendar Popup, List View and Mini Calendar Popup.

Closing this issue.

**Comment by paaljoachim** [comment]
> The List view and Calendar popup should be equivalent; I'm actually not totally sure I should even have separate settings for them - if they're different, that opens the possibility that users on mobile could see incomplete information, which is fuzzy.
> 
> However, since a user could disable one or the other view, as well, that makes things complicated. For now, I want the List and Popup defaults to be the same.

I am not sure what to say here. It sounds like you are saying that we need an issue to where we merge Calendar Popup and List View into one tab. As that would make things a little easier. 

I added a new event and checked out the Popup vs List View and as you say these should likely be the same. As they are almost identical anyway.
