### ISSUE TITLE
Event screen: Should Special Scheduling Options by default be hidden?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#277]
The reason why I am wondering if the Special Scheduling Options should by default be hidden is that it feels very niche oriented.

1-
It would be unchecked in Output Settings.

![Screenshot 2021-10-10 at 16 21 17](https://user-images.githubusercontent.com/5323259/136699793-13ad30b6-fcab-487d-87d4-11079fdeadf7.jpg)

2- 
Another approach might be to have Special Scheduling Options as a button that says + Special Scheduling Options. (Disclosure toggle) Similar approach to opening "+ Add a new location."

The options would not be seen unless the user decides to click to click the button link + Special Scheduling Options.

![Special-scheduling-Options-button](https://user-images.githubusercontent.com/5323259/136700187-6659d113-5654-4adf-bc4f-2d23a84eae90.jpg)

This way one can hide the contents inside the section. It gives a signal that the contents inside is not important for most users and that is why it is hidden.

**Comment by joedolson** [comment]
This got me thinking, and I can definitely improve this; but it would be a very different path than this. 

The "special scheduling" options, ultimately, are both settings specific to recurring events. So, 

1) They should be shown in the recurring settings panel, not have their own remote panel.
2) The individual options should only show when relevant. Holiday category should only be shown if an event is made recurring & a holiday category is configured; skipping 5th week should only be shown if the recurring event happens on the 5th instance of that date in a month, since otherwise it's irrelevant.

Showing these options only when they're relevant will make them infinitely clearer, and allow me to completely remove the language 'special scheduling options', which has always bothered me.

**Comment by paaljoachim** [comment]
That sounds like a very good idea Joe!

**Comment by paaljoachim** [comment]
Special Scheduling Options have been removed from the event screen.

![Screenshot 2021-10-10 at 18 56 50](https://user-images.githubusercontent.com/5323259/136705880-8ac2d66a-ba52-41ee-aee4-bd0677d10ed3.jpg)

As well as the - Settings -> Input screen.

![Screenshot 2021-10-10 at 19 01 05](https://user-images.githubusercontent.com/5323259/136705901-c3662689-1270-461f-bcc2-3d98106840c2.jpg)


They still need to be removed from the Screen Options area (atleast I am still seeing them there.)
Reopening this issue.

![Screenshot 2021-10-10 at 19 00 43](https://user-images.githubusercontent.com/5323259/136705916-a178b58f-601d-459e-8ae0-346866fa4fa5.jpg)

**Comment by joedolson** [comment]
Yeah, I made the change but failed to save those changes before committing. It's done now, but I didn't connect the commits.

**Comment by paaljoachim** [comment]
Special Scheduling Options has also been removed from the event screen - Screen Options.
