### ISSUE TITLE
Location Drop-Down list no longer works

### ISSUE THREAD

**Issue by dstevray** [joedolson/my-calendar#29]
It appears that the Location drop-down list has been changed to a simple text box. Is there any way of getting the drop-down back?

**Comment by joedolson** [comment]
The location drop-down has been changed to an autocomplete search that triggers when there are more than 25 locations. In the next release I'm changing the default trigger to 50 locations, because this switch is triggering too soon, but you can also pass a custom limit using the filter `mc_convert_locations_select_to_autocomplete`
