### ISSUE TITLE
Add Event screen: Adjusting occurrence

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#290]
Regarding Date and Time.
Let's say that I add a 3 day conference. Date 2021-10-12
End Date: 2021-10-14

I see the 3 day conference in the calendar as I would any other event.

----

![Screenshot 2021-10-12 at 12 48 12](https://user-images.githubusercontent.com/5323259/136942133-ea30cd5b-4766-44b1-80b5-929ba25fbd1c.jpg)

I click "Add occurrence" 
![Screenshot 2021-10-12 at 12 49 04](https://user-images.githubusercontent.com/5323259/136942250-70115260-bcce-4a1f-b471-3aa693e9a776.jpg)

The placement of "+ Add occurrence" changes.

Now we suddenly see a "This is a multi-day event" I am confused why we did not see this option with the other checkboxes in the original event. As the option to show as multi-day event on the frontend should be for the original event and any occurrence the user adds. 

Suggested adjustment.

![Event-adjusting-occurrence](https://user-images.githubusercontent.com/5323259/136943559-ee1d581a-8752-496b-82e9-479a971f368e.jpg)

1- "- Add occurrence" to close just like closing categories and location.
2- Moving "This is a multi-day event" next to "All day event". 
3- Removing the bottom ? tool tip that shows up next to "+ Add occurrence". It is better to have one tooltip for one feature, and to keep it next to the top "Add occurrence".

The fix also shows the occurrence button + tooltip in the same placement as before it was clicked.

**Comment by joedolson** [comment]
When you say:

> Clicking + Add occurrence adds an occurrence and opens up to reveal the new occurrence.

It sounds like you have the impression that clicking + Add Occurrence actually adds something. Technically, it only adds a *potential* new occurrence; the occurrence itself won't be added until after you save the event. 

> What do you think about moving the "This is a multi-day event" up and to the left of "Hide end time" ?

Thinking about it. I worry that it would make the checkbox almost invisible, so users would just miss it, as it would blend in with the other settings. From an accessibility perspective, it would actually be better to move it so that it appears after the event occurrence inputs. As it is, I'm adding a new field *above* the current focus point, which will make it very hard to ever find non-visually.

**Comment by paaljoachim** [comment]
> It sounds like you have the impression that clicking + Add Occurrence actually adds something. Technically, it only adds a potential new occurrence; the occurrence itself won't be added until after you save the event.

As I click + Add occurrence it seems to add a new occurrence. It automatically adds the same time but date is not filled in. (It is helpful to have the time automatically added in as it currently does.)

![Screenshot 2021-10-29 at 23 07 50](https://user-images.githubusercontent.com/5323259/139501810-726133cc-b04c-4412-9e0a-653a3dac3f02.jpg)


Saving the event as a draft I see this:
![Screenshot 2021-10-29 at 23 08 45](https://user-images.githubusercontent.com/5323259/139501918-4f5d53eb-c1b9-42d9-bda3-0180702138c2.jpg)



Link URLs:
https://my-calendar.dev.cc/wp-admin/admin.php?page=my-calendar&mode=edit&event_id=6
https://my-calendar.dev.cc/wp-admin/admin.php?page=my-calendar&mode=edit&event_id=7

----------

My Events:
I see the occurrence added even though it is identical to the original event.
![Screenshot 2021-10-29 at 23 09 53](https://user-images.githubusercontent.com/5323259/139502070-55e75fc3-892a-4333-92fb-690844012f83.jpg)

Going to an event and clicking Scheduled dates for this event I see this:
![Screenshot 2021-10-29 at 23 11 38](https://user-images.githubusercontent.com/5323259/139502201-11eccc50-6418-4be6-acfc-90e0bbef7abf.jpg)

-------------

So a few things. An occurrence is actually automatically added when clicking + Add occurrence.
Looking at the My events screen they have the same time and date.
Clicking each of the events and then looking at Scheduled dates for this event. It has the same event but now instead of the same time is says 1:00 pm - 10:00 pm (original time for the events is 12:00 - 21:00.)

So this is fairly weird.

**Comment by paaljoachim** [comment]
> Thinking about it. I worry that it would make the checkbox almost invisible, so users would just miss it, as it would blend in with the other settings. From an accessibility perspective, it would actually be better to move it so that it appears after the event occurrence inputs. As it is, I'm adding a new field above the current focus point, which will make it very hard to ever find non-visually.

My main reasons for moving " This is a multi-day event." is that it seems to belong close to the "All day event" checkbox. It also looks better having it beside the other checkboxes.
We could also move it after. Do you mean something like this?

![This is a multi-day event](https://user-images.githubusercontent.com/5323259/139503171-c83f0d77-a667-42cd-a81a-c82b32db9f43.jpg)

**Comment by joedolson** [comment]
It may help you understand what 'Add Occurrence' does by describing it differently. It's essentially the same as duplicating the event: it creates a copy of the current event with different date/time. But clicking 'Add Occurrence' does not create a copy; it just exposes the fields. If those fields are present when the event is saved, a duplicate event will be created.

Re: multi-day event checkbox.

It would need to be after all of the event occurrence boxes, because it applies to the whole collection, not to an individual copy.

It is related to 'All day', except that it only means anything at all for multiple copies of an event.

The time difference you're seeing (12pm vs 1pm) may be due to a timezone difference with your MySQL config. The displayed time is based on the MySQL configured timezone, so if that's wrong, you'll get some weird time results. But I can check that out. Try it in a live environment to double check.

**Comment by paaljoachim** [comment]
I am working on a documentation for adding an occurrence right now, and will add additional comments in a few moments. One thing that came up is...
Should "+ Add occurrence" change to "+ Add Occurrence" (capital O)?

**Comment by joedolson** [comment]
> As the option to show as multi-day event on the frontend should be for the original event and any occurrence the user adds.

This only means anything if there are multiple occurrences. Example use case:

_User enters three days of a conference. This could be entered as a single event that runs from October 31st - November 2nd, but the conference starts and ends at different times each day. The user wants to show each day's separate start/end times, but wants upcoming events lists to show the conference as one event. Adding these as three occurrences with the multi-day option checked allows the grid views to show individual dates/times while upcoming events shows the conference with a start and end date._

It's an edge case; but it's a tricky situation to figure out.

**Comment by paaljoachim** [comment]
Selecting events to become Multi day events.
I thought that selecting Multi Day events that these would show a little different on the frontend, but these looks just like any other events.

![Screenshot 2021-10-31 at 23 37 31](https://user-images.githubusercontent.com/5323259/139603477-7ef01a0c-08ce-4085-9a3d-1dd89ae7610a.jpg)

**Comment by joedolson** [comment]
Only different in list views; doesn't effect views that are lists of dates, only views that are lists of events.

**Comment by paaljoachim** [comment]
I will go ahead and close this issue....
