### ISSUE TITLE
Design -> Scripts

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#293]
I notice the checkboxes for disabling various JS and an AJAX setting, but I do not know what these do.

![Screenshot 2021-10-13 at 19 50 40](https://user-images.githubusercontent.com/5323259/137186630-c19c47cf-a3b8-48a9-bae6-0f6c418d15ed.jpg)

Should there be a sentence or two adding a short explanation of what these settings do?

**Comment by joedolson** [comment]
They seem fairly self explanatory to me; what is the confusion?

Disable Grid JS disables the JS running in grid view; list in list view; mini for the mini calendar; and AJAX disables all of the asynchronous JS.

**Comment by paaljoachim** [comment]
To me it is uncertain what actually happens when disabling these options.
Another option is to add the ? (tooltip popip), so the user can click it to gain more information on what actually happens. I will also create documentation for this as well. Giving examples. I will just need to explore what the result is when clicking each of the disable checkboxes.

**Comment by joedolson** [comment]
Do you mean that you need an explanation of how things *do* work when these options are disabled, rather than just the statement that the JS will be turned off? Because, practically speaking, I just don't understand how to describe that. "The things controlled by scripts won't be controlled by scripts."
