### ISSUE TITLE
Double scrollbar in Widgets screen.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#321]
I am seeing a double scrollbar like so.
Appearance -> Widgets. On the right side are two scrollbars. One inner for the widgets. One outer for.... hmm I do not know.

https://user-images.githubusercontent.com/5323259/138178177-bc931763-a7b4-4d9c-a921-665b43968fbe.mp4

Notice the white top left space.

**Comment by joedolson** [comment]
I don't think that has anything to do with My Calendar; the outer scrollbar you're seeing is the browser scrollbar. It's just appearing because the admin sidebar menu is longer than the height of the viewport.

It's also true if My Calendar is disabled, and you shorten the viewport enough to require scrolling.
