### ISSUE TITLE
Locations > Manage Locations

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#335]
Another screen I am also looking at is Locations > Manage Locations.

![Screenshot 2021-10-30 at 21 43 18](https://user-images.githubusercontent.com/5323259/139556576-1120ad30-c265-4ce8-964e-db4b2f22a752.jpg)

Can we rename the screen "Manage Locations" to just using "Locations"?
Similar to what we just did with the Categories screen.

Should the first location added automatically start out as the default location?

I am also seeing the Update your location permalink slug on the right side. I believe you told me some time ago that we needed to leave the "Default Location" area on the right side as seen in the above screenshot. Even though it would look better to have it just below the Manage Locations list.

**Comment by paaljoachim** [comment]
Btw I think I brought up the following some time back as well.
Clicking to edit a location switches focus from the sidebar "Locations" to "Add New Location"

**Comment by joedolson** [comment]
The demo content would pose a problem for setting the first location added as the default location. Also, some sites will use locations but not have all events have a location, in which case having an automatically set default location would be an annoyance.

I think the narrow benefit to auto-setting a default location is counterbalanced by the potential problems with it. 

Renaming the screen is fine.

Below the manage locations list would be very hard to find for sites with a large number of locations, although from an linearized perspective it wouldn't actually change the location. 

But this conversation has made me consider another way of doing this:

1) Add the 'Set location permalink' link as an inline link with screen header. (Similar to 'Add New' in other admin screens.)
2) Rather than showing the default location in the sidebar, automatically place the current default location first in the manage locations table, so it's always highlighted and easily found, but not out of context.

**Comment by paaljoachim** [comment]
That sounds like a good way of handling it!

Btw I am seeing this error:
Notice: Undefined variable: view_link in /Users/paaljoachimromdahl/Sites/my-calendar.dev.cc/wp-content/plugins/My Calendar/my-calendar-location-manager.php on line 321

![Screenshot 2021-10-31 at 23 19 34](https://user-images.githubusercontent.com/5323259/139603055-66013644-7315-4e13-9333-03507f5376c1.jpg)

**Comment by paaljoachim** [comment]
I added the newest update of the plugin to another of my local dev sites. I am now seeing this:

![Locations](https://user-images.githubusercontent.com/5323259/139605150-1a619be1-e37e-42f0-a5a6-edd3b0a01af5.jpg)

I assumed I would see the "Update location permalinks button" next to the Add New button.

**Comment by joedolson** [comment]
Fresh install? That's strange; I'm not sure why you wouldn't see that. It's just checking whether or not the option has a value.

**Comment by paaljoachim** [comment]
It works! Closing issue. (I do not know why it did not show correctly for the other dev site, but for the regular local dev site I am using it works nicely.) 

![Locations](https://user-images.githubusercontent.com/5323259/139732309-1583255c-5a25-4a77-8cda-f1b379972923.jpg)
