### ISSUE TITLE
Recurring events: Every 5 weekdays until 2021-11-19 does not look correct

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#349]
I just tested recurring events: Every 5 weekdays until 2021-11-19

![Screenshot 2021-11-05 at 11 13 35](https://user-images.githubusercontent.com/5323259/140494902-ac380f40-cdf4-49c8-bed4-2497f43adc02.jpg)

Starting november 6th (Saturday). Because it is a weekend the first event should be Friday.
Every 5 weekdays. Mon, Tues, Wed, Thur and it should then be on Friday. Nov 12. 
Next should be again on Friday Nov 19th.

As I assume that this means every 5th weekday there is an event.

This is what I see:

![Screenshot 2021-11-05 at 11 14 35](https://user-images.githubusercontent.com/5323259/140495296-af820cee-ffdd-4da3-a945-346f12148ab3.jpg)

**Comment by paaljoachim** [comment]
It seems that in general the Repetition patterns are not working correctly.
I made a new issue for it here: https://github.com/joedolson/my-calendar/issues/350

**Comment by joedolson** [comment]
Here's a question worth thinking about: how useful is this type of repetition? Is there a situation where it's actually useful? It's very unpredictable: every 5th weekday? 

It only exists because that's the way the settings are, but it seems kind of dubious. I can totally see the logic of an even that repeats daily for 10 days only on weekdays; but that appears every 3 weekdays? (Monday, Thursday, Tuesday, Friday, etc...) -- that seems pretty weird.
