### ISSUE TITLE
Add Generate Shortcode button to My Calender Page shortcode meta boxes.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#362]
It would be nice to add the "Generate Shortcode" button from here:

![Screenshot 2021-11-13 at 00 37 05](https://user-images.githubusercontent.com/5323259/141595666-8d9aa241-ebd0-4081-9b9e-3a13cee46fc6.jpg)

Into the My Calendar page shortcode generator meta boxes.
![Screenshot 2021-11-13 at 00 33 39](https://user-images.githubusercontent.com/5323259/141595689-fe124bc2-1be4-4433-83ae-b22ba797816b.jpg)

This way one can create the shortcode in the My Calendar page. Click Generate Shortcode and view the shortcode before saving the content of the page. + We would also have additional consistency between both types of Shortcode generators.

**Comment by joedolson** [comment]
Maybe in 3.4. Would require making the shortcode generator work via AJAX, so too much to change this late.

**Comment by paaljoachim** [comment]
Yeah. Moving to 3.4.0 is a good idea at this stage.

**Comment by joedolson** [comment]
I've been thinking about this, and honestly it may make more sense to *remove* the shortcode output on the main calendar metabox. I think it's giving a wrong impression, since you don't actually need to use it on that page - if you adjust the shortcode settings on the main calendar page, they'll be used whether they're in the shortcode or not. It's using the same code as the shortcode builder, but it's actually saving meta data on the post.

**Comment by joedolson** [comment]
Shortcode is hidden following https://github.com/joedolson/my-calendar/commit/d2c3f8410f5d1610d21f5bb1aa905669b0b8f35d; closing.

**Comment by paaljoachim** [comment]
Brainstorming....

I go to the My Calendar page. See the default shortcode: `[my_calendar id="my-calendar"]`
Notice the My Calendar Display Options below. I wonder how I can use it. Questions such as...
Can I create a new display/view here by clicking various options such as to show specific categories?
Going through the options. How would I save the options I select? As currently there is no way to save or generate a view/display that I can use instead of the default shortcode.
I am not sure of the purpose of seeing the My Calendar Display Options when I can not save anything of the adjustments that I make.

**Comment by joedolson** [comment]
So, why do you see this meta box as different from other meta boxes? All common meta boxes are based on updating when you save the post; that's a long-standing standard way for post meta boxes to work. 

Do you see this as different because you had previously seen it as a shortcode builder, or is there something about this meta box that makes you think that you can't save the settings like you normally would?

**Comment by paaljoachim** [comment]
> So, why do you see this meta box as different from other meta boxes? 

I have not used a lot of meta boxes so that I am not certain how these do work.

So it seems that a meta box one makes a selection does something and it will be reflected after updating the page.
I made a selection and updated the page. I did though expect the default shortcode to change to reflect the selection I made in the meta boxes. (Such as change Format to List.) But the backend shortcode remains the same. The frontend calendar showed the adjustment.

Which means I can have a Shortcode which is not the same as the calendar viewed in the frontend because I made adjustments in the Display Options.

**Comment by joedolson** [comment]
In fact, you don't need the shortcode at all. The shortcode is only needed to determine where in the page content the calendar will render; if it's missing, the calendar is appended to the end of the content.

**Comment by paaljoachim** [comment]
Ahh That is interesting to know.
I think we might need a question ? bubble somewhere around the Meta boxes title with a link to a documentation page speaking about these things. As the user would be able to get more information about how the meta boxes work.
