### ISSUE TITLE
Stylesheet Twenty Twenty vs Twenty Twenty One.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#389]
twentytwenty.css

![Screenshot 2021-12-02 at 08 53 27](https://user-images.githubusercontent.com/5323259/144380454-2cf54c9b-51ae-4d28-914c-065fd0e34306.jpg)

twentytwentyone.css

![Screenshot 2021-12-02 at 08 49 44](https://user-images.githubusercontent.com/5323259/144379994-a0771712-922a-4246-927b-b4e9a97a42ec.jpg)

These are almost identical.

I will create a few explorations for the new twentytwentyone.css stylesheet.

**Comment by paaljoachim** [comment]
Here is an example with removing the blue background gradient.

![Screenshot 2021-12-02 at 17 14 33](https://user-images.githubusercontent.com/5323259/144460225-a5cf6c51-45f0-4e97-ac01-41a75a117a6f.jpg)

**Comment by joedolson** [comment]
Avoid adding colors to stylesheets; try to do any color experimentations using the provided CSS variables. That allows people to change colors without editing the code directly.

Note: I have no problem adding variants of stylesheets, as well. Only one will be default (obviously), but adding multiple variants is fine.

And yes, the two look largely identical. The main reason for adding new stylesheets is so that the default stylesheet supports any changes made to the output HTML...

Be sure to also review in list, mini, and single event views.

**Comment by joedolson** [comment]
Also, with any styling, be sure to check it in a variety of themes.

**Comment by paaljoachim** [comment]
Here is another variation.

![Screenshot 2021-12-03 at 23 53 02](https://user-images.githubusercontent.com/5323259/144683173-af52c24e-77d1-4aa4-af04-eb6797cad0cd.jpg)

I added a "few" CSS Variables....
![Screenshot 2021-12-03 at 23 53 42](https://user-images.githubusercontent.com/5323259/144683235-1eada616-e94b-4a64-a756-749cce19d9aa.jpg)

It works well in various views and in various themes.

CSS code that I added:

```
/* Calendar max width. */
#my-calendar {
	max-width: 1000px;
}

/* Top calendar menu items. */
.mc-main .my-calendar-header {
	column-gap: 35px;
}

/* Month, Week and Day */
.mc-time {
	padding-right: 5px;
}

a.month,
a.week,
a.day {
	background: var(--buttons-opt2);
	border-radius:9px;
	display:inline-block;
	cursor:pointer;
	color:#ffffff;
	font-family:Arial;
	padding: 8px;
	text-decoration:none;
}

span.mc-active.month,
span.mc-active.week,
span.mc-active.day{
	background: var(--buttons-opt1);
	border-radius:9px;
	display:inline-block;
	cursor:pointer;
	color:#ffffff;
	font-family:Arial;
	padding: 8px;
	text-decoration:underline;
}

/* Select month - Year drop down */
select#my-calendar-month,
select#my-calendar-year {
	border: 2px var(--buttons-opt1) solid !important;
	font-size: 1.3em;
}

/* Go button */
input.button {
	background: 4px var(--buttons-opt1) !important;
	border: 2px var(--buttons-opt1) solid !important;
}

/* Go button hover */
.mc-main .my-calendar-header input:hover {
	background: var(--buttons-opt1) !important;
	border: 2px var(--buttons-opt1) solid !important;
	color: var(--primary-light);
	cursor:pointer;
}



/* Left and Right arrows */
.my-calendar-nav {
	padding-left: 1em;
}

/* Calendar numbers heading */
span.mc-date {
	background:  var(--calendar-date-headings);
}

/* Calendar dates */
.mc-main td {
	border: 1px var(--calendar-dates-border) solid !important;
	height: 8.5em !important;
	background: var(--calendar-dates);
}

/* Calendar current day */
.mc-main .current-day {
	background: var(--current-day) !important;
}

/* List View - Remove dot infront of the date. */
.mc-main .mc-list {
	list-style-type: none;
}

/* Mini View */
.mc-main.mini td {
	height: auto !important;
}

```

**Comment by joedolson** [comment]
I like adding a max-width; it will only have an impact on themes that follow the block theme pattern, but that's a growing base, certainly.

Can't use `#my-calendar` as an ID, however, since it doesn't necessarily exist. `.mc-main { max-width: 1000px ! important }` should work, though. I'd be inclined to add it to the base CSS (reset.css), since it's going to be valuable for all stylesheets - they'd all benefit from that.

Otherwise, I'm not sure how easily I can use this; it's a good example of what somebody could do, but isn't something currently possible. Keep this in mind, though - it will play well with my plans for templating changes in 3.4.

**Comment by paaljoachim** [comment]
I have updated this doc along the way as I was experiementing:
https://docs.joedolson.com/my-calendar/my-calendar-design-style-editor/

Let me know if you would like me to continue the exploration. As it seems this is helpful for you to see how I go forth in creating a stylesheet.

**Comment by joedolson** [comment]
Certainly. Might be worth while to note in the docs that custom variables were introduced in twentyeighteen.css, and don't exist in earlier sheets; also to specify which sheet you're doing color experimentations in, since they won't have the same effect in every stylesheet.

**Comment by paaljoachim** [comment]
Good idea! I added in this information:
CSS or custom variables were introduced in twentyeighteen.css, and do not exist in earlier stylesheets. Only twentyeighteen.css, twentytwenty.css or newer stylesheets contain CSS variables.

I also added in information about which stylesheet I was experimenting with.

I added new information about using ones own custom stylesheet.

**Comment by joedolson** [comment]
Just for clarity, I think it's more accurate to say "are not present" in earlier stylesheets. They can be used in any stylesheet; but the older stylesheets haven't been retrofitted to use them.

**Comment by paaljoachim** [comment]
> Just for clarity, I think it's more accurate to say "are not present" in earlier stylesheets. They can be used in any stylesheet; but the older stylesheets haven't been retrofitted to use them.


Good point!
