### ISSUE TITLE
Design > Style Editor - rephrasing

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#396]
The text: "Edit the stylesheet for My Calendar" located here:

![Screenshot 2021-12-04 at 22 07 43](https://user-images.githubusercontent.com/5323259/144724618-8678a389-c4d0-4709-a0e2-05e4cedfdf6a.jpg)

could instead say: "Edit a My Calendar stylesheet."

**Comment by joedolson** [comment]
Or it could specify which one is being edited, which might be better than either.

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/my-calendar/commit/341100676fe80789c484856653c98649a6376ca1

I also changed "Use your own styles" to "Disable My Calendar CSS". That's what it does; disables the My Calendar CSS. Use your own styles implies that checking this box will somehow provide a method to add your own styles.

**Comment by paaljoachim** [comment]
This is a lot better!

![Screenshot 2021-12-05 at 20 32 54](https://user-images.githubusercontent.com/5323259/144760863-914d5856-e2d7-4691-ad5b-449647205633.jpg)
