### ISSUE TITLE
Adjustments done in former installed plugin follows through to new reinstall.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#413]
When clicking Settings > General - Drop MySQL tables on uninstall and Delete plugin settings on uninstall. 
I assume any adjustments done to My Calendar will not show up upon reinstalling the plugin.

As I am testing this issue: https://github.com/joedolson/my-calendar/issues/26

I noticed that adjustments made to My Calendar Display Options (Meta Boxes) are not being removed on the uninstall but these follow through to the next reinstall of the plugin.

Example is adding exports to the Navigation below calendar. Is still seen in the reinstall.

![Screenshot 2021-12-13 at 01 11 22](https://user-images.githubusercontent.com/5323259/145735331-36c4abff-a420-448b-8eed-668d4a609018.jpg)

**Comment by joedolson** [comment]
Hmm. I'm not sure whether I should remove that; it's not plug-in settings, it's post meta data. I also don't remove the existing My Calendar page that's associated with it, because I don't have any way of knowing what *else* is on that page. It could be just the My Calendar shortcode, but it could be that the shortcode is built into a complex layout with supporting content.

I wouldn't choose to remove the page, but I could remove the post meta data.

**Comment by paaljoachim** [comment]
I look it like this. Anything a plugin adds to the database should be removed on uninstall if the user clicks to remove everything on uninstall. (I understand that the featured image and page remains and can also manually be deleted by the user. Anything in the database can be more difficult to remove.)

**Comment by paaljoachim** [comment]
I reinstalled and noticed that the "exports" shortcode is still seen in the newly uploaded plugin.
What adjustment did you make?

**Comment by paaljoachim** [comment]
I removed the plugin again. Did some hard refreshes again and this time it seemed to be working correctly.
The "exports" shortcode is removed from the Meta Boxes - My Calendar Display Options. 
Great!
