### ISSUE TITLE
Location Regression?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#416]
Hey Joe

I am wondering if we have a Location regression. There are some problems with the Quick edit View and seeing the map on the frontend Location view.

I made this video:
https://youtu.be/KV_5nn2RIRM

**Comment by joedolson** [comment]
In general, try not to open a single issue with multiple concerns; it makes things harder to close. I think the issues here are

1) Demo location created without a post reference, causing no reference link.
2) Map not rendering on front-end view for locations.

For the 2nd: can you confirm that was the latest version of files? I saw in the video that you used a zip generated at 10:50 your time, but without knowing what it was generated from, that doesn't tell me much.

**Comment by paaljoachim** [comment]
Here I wanted to highlight what I noticed. Then split it up into separate issues.
Here is the map no rendering on the frontend view for locations issue: https://github.com/joedolson/my-calendar/issues/417

I assume we can take number **1. Demo location created without a post reference**, causing no reference link. onward in this issue.

It was the latest build taken from Github this morning at 10:50.

**Comment by joedolson** [comment]
So, the demo location was actually created correctly; it was a bit more complicated than that - it was leftover data from a previous install that was being picked up. Working on it. It's not a bug that would come up very much in a live installation, since most people aren't constantly installing and uninstalling various versions, but it's not impossible!

**Comment by paaljoachim** [comment]
Glad to hear that you were able to remove the leftovers..:)
