### ISSUE TITLE
Event location: events that use a deleted location will still show the location on the frontend

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#420]
Added a location through the Location Manager.
Added an event and added the location.
-
Deleted the location through the Location Manager.
Frontend: My Calendar -> clicking the event (popup): shows the deleted location -> clicking read more (Single event view) deleted location is also seen here.

I did a few hard refreshes to be sure that the location was not in the cache.

**Comment by joedolson** [comment]
This is actually a result of how the data is managed, and is a pretty major project to change, because it requires a significant database change. On my radar, but not soon. 

Basically, the event stores a copy of the location fields for the location you associate it with. (Dates back to before there was a location manager.)

**Comment by joedolson** [comment]
Moving to 3.5.0; this requires significant DB stuff.

**Comment by joedolson** [comment]
- [ ] Rewrite location filters to use JOIN clauses with location table
- [ ] Update event saving to only write location data to location table
- [ ] Update event fetching to only pull locations from location table
