### ISSUE TITLE
Automatically fill out https:// in a field that uses a link?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#474]
**Is your feature request related to a problem? Please describe.**

I am adding an event. Under Event Details I added a site to More Information. I did not fill in the https:// information, so when saving the event as a draft I noticed this message:

![Screenshot 2022-10-17 at 16 32 39](https://user-images.githubusercontent.com/5323259/196205191-305ce73c-ee98-4de1-961e-7ad46aad7d37.jpg)

**Describe the solution you'd like**

Should https:// automatically be added to link information?

**Describe alternatives you've considered**

Manually adding in https://

**Comment by joedolson** [comment]
Might be suitable as a placeholder, to encourage users to add it; but automatically adding it could lead to problems, if a target site doesn't have an SSL cert.

**Comment by joedolson** [comment]
Looks like this already has a placeholder; did the placeholder not show up?

**Comment by paaljoachim** [comment]
I retested and made another event.
The placeholder is not seen. I do get the message: "Please enter a URL."  As it is looking for http:// or https://

![Screenshot 2022-10-18 at 08 59 33](https://user-images.githubusercontent.com/5323259/196358845-97d7c7a0-7cee-4d2b-80c7-de91f6235b7b.jpg)

**Comment by joedolson** [comment]
That screenshot doesn't really show me anything, since a placeholder is only visible before you add content to the field. 

![image](https://user-images.githubusercontent.com/1686451/196468624-364f1c20-a4a7-4bf4-a12a-f42f9748429e.png)

Do you see that before adding content? If not, that's a concern. If you do, that's all I'm going to do. The "Please enter a URL" is browser validation for a URL input that doesn't have valid content.

**Comment by paaljoachim** [comment]
I appologize Joe. This is a duh not thinking moment. I am seeing the placeholder. 
I will go ahead and close this issue.
