### ISSUE TITLE
Multiple languages drop down - ? bubble not clickable

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#563]
**Describe the bug**

The various ? bubbles are blue and clickable.
When multiple languages are used the ? bubble is black and not clickable.

**To Reproduce**
1. Add another language.
2. Beside the language dropdown. Notice the black ? bubble is not clickable.

**Expected behavior**
Having the same clickable behavior as other ? blue bubbles. 

**Screenshots**

![Screenshot 2023-08-15 at 16 27 32](https://github.com/joedolson/my-calendar/assets/5323259/7ac7aa56-4191-49b8-b983-b530fc2fd549)

Brave browser. Using WordPress 6.3. Theme: Twenty Twenty Three.
My Calendar version 3.4.17

**Comment by paaljoachim** [comment]
The various ? bubbles in an event page is blue and clickable.

I noticed that example Settings Text has the same type of black ? bubbles as beside the languages drop down.

**Comment by joedolson** [comment]
I'm not inclined to make this change. I'm using the blue help icons to open modals with help information when the amount of information is too long to easily display directly on screen; otherwise, it's just an icon. 

I can remove the gray icons, I suppose, but I'm not convinced that would be helpful.

**Comment by paaljoachim** [comment]
Ok. I brought it up as it might case some questions as to why it is there.
I will go ahead and close this issue.
