### ISSUE TITLE
Clicking Publish button does not change the name to published/update/save.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#71]
Hey Joe

What I mean here is that a new event the Publish area looks like this:

<img width="375" alt="Screen Shot 2021-06-27 at 19 35 05" src="https://user-images.githubusercontent.com/5323259/123554116-de475500-d77e-11eb-8694-2160c7ba4cfa.png">

It looks like the event is already published.

Clicking the Publish button. I see this:

<img width="805" alt="Screen Shot 2021-06-27 at 19 36 33" src="https://user-images.githubusercontent.com/5323259/123554148-03d45e80-d77f-11eb-9d3b-aaadeeb9475a.png">

There is no visual change before one has published an event and after it has been published.

Step 1. Before having saved/published for the first time.
Button can say Publish. The drop down next to it where it todays says Published could perhaps also say Publish.

Step 2: The publish button has been clicked, and the button word could change to reflect that the event has been published. It could now say "Update" (As can be seen in Gutenberg) or "save".
The drop down next to it could now say Published.

Example from Gutenberg: 

Before publishing:
<img width="341" alt="Screen Shot 2021-06-27 at 19 44 15" src="https://user-images.githubusercontent.com/5323259/123554396-17cc9000-d780-11eb-96cd-8f71ee99148e.png">

After having published:
<img width="356" alt="Screen Shot 2021-06-27 at 19 43 27" src="https://user-images.githubusercontent.com/5323259/123554386-02effc80-d780-11eb-97bb-532838c03dd5.png">

Step 3: As it would be nice to go back to an event and instead of clicking the button "Publish". One clicks the "Update" button.

**Comment by joedolson** [comment]
Re: 3. Currently, if you go to edit an event, the button says 'Edit'. Happy to change it to update; that matches other things in WP better.

**Comment by joedolson** [comment]
(Sorry, it says 'Save', not 'Edit')

**Comment by joedolson** [comment]
This would be a fairly major workflow change, since right now the form is biased for sequential creation of events, rather than create-then-edit. This because my experience indicates that the most common work flow is to create a series of events for the calendar, each with fairly simple data, but doing several in a row. As a result, the default action after publishing an event is to clear the form and prepare it for creating another event; in which case 'Publish' is appropriate.

I did just add a link to the status message so that a link to edit the newly-created event is available for immediate editing, should that be required. 

With that, I'm going to close this - thanks! The exploration did result in some improvements to the UI, even if not what you were imagining.

**Comment by paaljoachim** [comment]
> With that, I'm going to close this - thanks! The exploration did result in some improvements to the UI, even if not what you were imagining.

Sounds great, Joe!
