### ISSUE TITLE
Adding a grey background to: "This is a multi-day event." (?)

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#76]
I am wondering if the "This is a multi-day event." should have the same treatment as in light grey background as other checkbox areas surrounding it?

![Screen Shot 2021-06-28 at 14 03 06](https://user-images.githubusercontent.com/5323259/123633725-dbe60900-d819-11eb-90bd-b944c5e4f901.png)

**Comment by joedolson** [comment]
I use that for checkbox groups, as a general rule, so I'm not sure I should. I'll think about it, though.

**Comment by joedolson** [comment]
I'm going to leave this as it is. Closing.

**Comment by paaljoachim** [comment]
As a user I wonder why the checkboxes above have a grey background and why the one below does not.
Anyhow it is a minor thing.

**Comment by joedolson** [comment]
As of https://github.com/joedolson/my-calendar/commit/e752dfef79f9a465900c3c21b1ebf5af50827c81, this design is a bit different; I added a secondary copy of the Add Occurrence button & placed both multi-date event specific controls in a container.

**Comment by paaljoachim** [comment]
Btw
I need to look into "This is a multi-day event" feature. As I wonder about it's purpose vs just adding multiple occurrences that in themselves  that are multi day events. Such as adding 2 events on the same day.

**Comment by paaljoachim** [comment]
I tested the Multi-day event and added 3 occurrences and then checked the frontend, but could not see any difference.
I will I believe just leave this aspect for now, and perhaps circle back at another time.

**Comment by joedolson** [comment]
Multi-day events has to do with how they're listed in upcoming events lists, if I remember correctly. When marked as a multi-day event, it's treated as a single event in upcoming events rather than having each instance listed separately. I don't know how often this is used - I don't know that I've ever used it myself, but there were at least a few users who depended on it. 

If I remember correctly, it was mostly conference venues, where they'd have multiple conferences occurring simultaneously, each with multiple entries, but didn't want each day of the conference to show up in the list separately.

**Comment by paaljoachim** [comment]
I searched the documentation, and you are right.
"For all editing purposes, multi-day events are identical to any other grouped event. In the group event manager, you can also join events into a multi-day event, if you have events which were added prior to this change in the plug-in and need them to be merged.
Multi-day events are primarily different in display. Rather than displaying each individual occurrence, you can show just a single item, with the date encompassing the entire span of the event."

I will circle back to it at a later time.
