### ISSUE TITLE
Repetition Pattern: Frequency number field changes size

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#78]
Add Event screen.

Repetition Pattern section.

Period:
Selecting "Monthly by day"
and
"Yearly" 

Changes the Frequency number field.

https://user-images.githubusercontent.com/5323259/123873245-7cc9e680-d936-11eb-9e8e-f6cb72e4fdbd.mp4

**Comment by joedolson** [comment]
Well. 

That's weird...

**Comment by joedolson** [comment]
So, the only change that's happening on that field is a change to the `max` attribute, because monthly by day only supports a frequency of 1 (can only do that pattern every month, it isn't supported for other options.)

But it's surprising that has an impact on the visual size of the field. 

Looks I can avoid that by declaring a specific width for that field in CSS, so I guess that's what I'll do.

**Comment by joedolson** [comment]
If you can verify this fix works on Mac, I'd appreciate it. I verified on Chrome for Windows, which exhibited the same issue, but haven't checked on mac.

**Comment by paaljoachim** [comment]
The fix works on my Mac in Chrome.

**Comment by joedolson** [comment]
Good enough for me. Thanks!
