### ISSUE TITLE
Location Editor: Country option needs a drop down.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#81]
The Location Editor: Country option today is a text field.

<img width="336" alt="Screen Shot 2021-07-03 at 15 42 06" src="https://user-images.githubusercontent.com/5323259/124356245-47aee400-dc15-11eb-98b2-247d80ec42c4.png">

It should be turned into a country drop down list.

**Comment by joedolson** [comment]
It's already possible for a user to set this up as a dropdown, and I'm not sure I want it to be limited to a preset collection. I'm already aware of at least one site that's using My Calendar for a calendar of fictional events, and this would break their set up. 

What I might want to do is implement an autocomplete that uses the location database as a data source, so that it helps ensure that countries are entered the same way consistently (which is the main reason for implementing a select, anyway.)

**Comment by paaljoachim** [comment]
Another option might be to have the text field as today and a country drop down. So the user can choose to insert a fictional country in the text field or select a country from the drop down.

**Comment by joedolson** [comment]
Actually, it could be an autocomplete that combines the location database with a pre-defined set of standard country names. That way it seeds the data for users, but doesn't prevent them from adding something different.
