### ISSUE TITLE
Making Single Event Details similar to Re-order calendar layout?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#85]
Output tab.

Re-order calendar layout currently looks like this:

<img width="973" alt="Screen Shot 2021-07-10 at 20 07 49" src="https://user-images.githubusercontent.com/5323259/125173066-5c631d00-e1bd-11eb-8436-5090f523cc2b.png">

The Single Event Details which currently looks like this:
<img width="875" alt="Screen Shot 2021-07-10 at 20 28 46" src="https://user-images.githubusercontent.com/5323259/125173086-7a308200-e1bd-11eb-8325-12c4f115cdbe.png">

Should the Single Event Details look like the Re-order calendar layout?
Which steps can we take to have these two areas look more similar to each other?

**Comment by joedolson** [comment]
It's certainly an option, although there's a lot of work to get there. Since the event details page doesn't currently have any method to change the order of elements, that's not really viable; and writing a new stylesheet would get tricky, since it would have to be able to reasonably support any order of items.

Also, as it is, not all of these items are in independent containers in the HTML; so some of them would need to be reordered as or within a group. 

It would have to be part of a major template overhaul. Definitely something I'm game for, but won't happen in this release.

**Comment by joedolson** [comment]
This won't be relevant in the next version of templates; they'll be PHP driven. Also, when I said "the event details page doesn't currently have any method to change the order of elements", I was wrong. Not sure why I was thinking that; there's a filter to do it:   https://joedolson.github.io/my-calendar/mc_default_output_order.html

Closing; I'm not going to add more features for legacy templating.
