### ISSUE TITLE
Event Occurence: Date listed in the wrong order

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#87]
Date example lists it as: YYYY-MM-DD
But it is actually showing as MM-DD-YYYY

![Screen Shot 2021-07-10 at 21 08 49](https://user-images.githubusercontent.com/5323259/125174077-18731680-e1c3-11eb-9db5-d0e13ea5d4ad.png)

It would be nice to clean up both the Date and End Date descriptions to reflect how it looks inside the field.

**Comment by joedolson** [comment]
I can't actually control what the field prompts for, since that's going to be dictated by the browser. Back when support for date inputs was a lot lower, providing a format hint was a lot more relevant - now, it's only relevant on Opera mini and IE11, so probably not worth keeping.

**Comment by paaljoachim** [comment]
I am not sure what you are saying here:

> Back when support for date inputs was a lot lower, providing a format hint was a lot more relevant...

Are you talking about the date hints inside the fields?
I just find it important that the Date YYYY-MM-DD is showing the correct order as will be used inside the field.

**Comment by joedolson** [comment]
I mean that the label can just be 'Date' and 'End date (optional)', because the date format is controlled by the input field, and it's no longer nearly as likely that somebody would be able to enter an invalid date string. When the date input type had less support, it would fall back to a text string, and that could create a lot of problems. 

It technically doesn't matter what format the date is entered as, as long as it's a valid structure.

**Comment by paaljoachim** [comment]
This works nicely:

![Screen Shot 2021-07-16 at 13 38 41](https://user-images.githubusercontent.com/5323259/125941989-83725ce7-0404-4a43-b6de-59ced0d776dd.png)
